services:
  java-chatgpt-api:
    build: .
    container_name: java-chatgpt-api
    image: linweiyuan/java-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - CHATGPT=true
      - PROXY=
    restart: unless-stopped